Soft-Craft-Tech/Pamba-Web

Docs/endpoints_documentation.md
=> updated endpoint docs

Docs/endpoints_documentation.md
=> add endpoint docs retrieve service

Docs/endpoints_documentation.md
=> change business_id to slug

API/appointments/routes.py
=> Handle invalid date exception for appointment booking

Docs/endpoints_documentation.md
=>  add endpoint book/web-appointments responses

Docs/endpoints_documentation.md
=> add endpoint messaging docs

Docs/endpoints_documentation.md
=> Documentation for fetch business reviews

API/appointments/routes.py, API/clients/routes.py, API/inventory/routes.py
- Allow Businesses to book in walk-in clients.
- N/A
=> Allow add appoinment fromm shop

API/sales/routes.py, Docs/endpoints_documentation.md
=> fix all services endpoint docs

API/lib/data_serializer.py, API/sales/routes.py
=> Add sale id to to the Sales Serializer

Docs/endpoints_documentation.md
- Add documentation for Appointment Reschedule Endpoint
- Changes to the Appointment Reschedule Endpoint
=> Add documentation for Appointment Reschedule Endpoint

API/businesses/routes.py
Edit single business payload
- Requested by frontend team
- Tested locally with postman
- N/A
=> Edit single business payload

API/appointments/routes.py, API/clients/routes.py, API/staff/routes.py
- This PR introduces comprehensive improvements to the Flask backend across the staff, business, and admi blueprints, enhancing reliability, consistency, and developer experience.
- Addresses #81 
- 
Payload Validation: Tested missing/invalid fields across endpoints (e.g., missing required fields, invalid formats) to 
verify 400 responses with clear messages (e.g., Invalid payload: {'field': ['Required']}).
Resource Creation: Tested creation endpoints to confirm 201 Created with serialized responses, including resource 
data.
- Include details of your testing environment, and the …
=> Adds Error Handling in Staff, Appointments and Clients routes

API/appointments/routes.py, API/businesses/routes.py, API/expense_accounts/routes.py, API/expenses/routes.py, API/gallery/routes.py, API/inventory/routes.py, API/lib/auth.py, API/sales/routes.py, API/services/routes.py, API/staff/routes.py
Added a decorator to ensure all businesses verify their emails before operations
It encourages more users to get verified early enough and start exploring the site
- N/A
- [X ] New feature (non-breaking change which adds functionality)
=> Business Verification Required Decorator

API/appointments/routes.py, API/businesses/routes.py, API/lib/send_mail.py, API/services/routes.py, API/templates/confirmAppointment.html
This fix ensures the endpoints match the new location details from accepting a map url to dynamically retrieving location fields from the google map API
- N/A
=> Ensure Location details match new Google API format

API/businesses/routes.py
I noticed we already had an enpoint to resend verification email. I just changed the check from active to verified to correctly check for email verification.
Addresses #94 
- N/A
=> Fix: Add is verified check to existing resend_verification_email endpoint

API/businesses/routes.py, API/models.py
As discussed, this updates the datetime object in the  models, and defaults business.active to True
Edit: I have removed the nullable=True from all but the Expense model description fields since it is the default model behaviour. The Expense model is set to nullable=False presumably to ensure expense accountability.
- N/A
=> Fix Datetime Object, Description, and Active Status

API/businesses/routes.py
Check whether the account verification token is expired.
- N/A
=> Feat: Check the the account verification token is expired

API/services/routes.py
Ensures only businesses that have activated, verified and  updated their profiles are shown to customers when they search for services.
- N/A
=> Fix: Add verified, active, and profile completion checks

API/appointments/routes.py, API/businesses/routes.py, API/clients/routes.py, API/lib/send_mail.py
Added error handling to ensure endpoints that send emails return errors gracefully
- N/A
=> Fix: Add error handling to email logic

API/appointments/routes.py, API/businesses/routes.py, API/clients/routes.py, API/lib/send_mail.py
Undo PR. Merge to dev branch instead.
=> Revert "Fix: Add error handling to email logic"

API/appointments/routes.py, API/templates/confirmAppointment.html
Returns a service object alongside appointment details
- N/A
=> Service object
